spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_des_reservations
    username: postgres
    password: 12345ali
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 60000  # Set the maximum amount of time that a connection is allowed to be idle (in milliseconds).
      max-lifetime: 1800000  # Set the maximum lifetime of a connection (in milliseconds).
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

